# Generated by Django 4.1.2 on 2022-10-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_testmodel_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modely',
            name='test_content',
        ),
        migrations.DeleteModel(
            name='ModelX',
        ),
        migrations.DeleteModel(
            name='ModelY',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
